import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { HeaderBar } from "../components/Organisms/HeaderBar";
import { SignInForm } from "../components/Organisms/SignInForm";

const SiginIn: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderBar />
      <SignInForm />
    </div>
  );
};

export default SiginIn;
